global:
    scrape_interval: 1m
     scrape_timeout: 10s 
    evaluation_interval: 1m
    external_labels:
        monitor: 'my-monitor'
scrape_configs:
    - job_name: 'prometheus'
      static_configs:
          - targets: ['localhost:9090']
    - job_name: 'node-exporter'
      scrape_interval: 5s
      static_configs:
          - targets: ['node-exporter:9100']
    - job_name: 'cadvisor-exporter'
      scrape_interval: 5s
      static_configs:
          - targets: ['cadvisor:8080']